### PR TITLE
Set up notebook prototype

### PR DESCRIPTION
**Pull request by mkcor**
Hello!

@bstdenis Thank you for providing a starting point for this work.

The notebook I'm submitting makes use of HTML widgets.  It's a first pass at interactive visualization... If you actually run it, it should look more like this:
interact_daily_pr_1960

@huard @tomLandry Please review!

### CODE REVIEW

**Comment by mkcor** [comment]
Ultimately I'd like to make this smarter and smoother (e.g., not rebuilding the entire image each time the user changes the `year` value), maybe in the spirit of [gganimate](https://github.com/dgrtwo/gganimate).

Also, for inspiration: https://plot.ly/python/geo-streaming/

**Comment by bstdenis** [comment]
Accessing the files via the thredds server requires doing the annual mean operations in multiple steps because of size limits on thredds (500 mb). e.g. a loop with ncvar[0:100,:,:] then ncvar[100:200,:,:] etc.

**Comment by huard** [comment]
Nice. I added a Use Cases [wiki page](https://github.com/Ouranosinc/data-visualization/wiki/UseCases) to discuss ideas about how visualization will be used in PAVICS. I think it's interesting to explore a
few different technologies before making our mind.

**Comment by Balinus** [comment]
cf. Exploring different technologies: Data Visualization Server : http://lightning-viz.org/

Supposedly designed for "large data sets and continuously updating data streams". Of course, I don't know how it incorporate within your codebase.

**Comment by mkcor** [comment]
Thanks for all the feedback!

@bstdenis I have taken your comment into account, so the data are now loaded from the THREDDS server, thanks! (https://github.com/Ouranosinc/data-visualization/pull/1/commits/764711b2c340f494b8d3a4222ae987c9e944904c)

Oops, I should now update the text to reflect this...

**Comment by mkcor** [comment]
Ready for final review!

**Comment by bstdenis** [comment]
:shipit:

**Pull request merged**
